### ISSUE TITLE
ToDo List BackEnd

### ISSUE THREAD

**Issue by matthiku** [matthiku/chatter#1]
- [x] (1) Improve Laravel Mix setup (BrowserSync etc)
- [x] (2) use username as login credential instead of email address
- [x] (3) Email confirmation
- [x] (4) Laravel Socialite with Google or GitHub authentication
- [x] (5) Routes: Move API-like requests into the API route file
- [x] (6) Add/integrate Laravel Passport
- [x] (7) Allow for multiple chat rooms - create Migrations and Models
- [x] (8) Allow for multiple chat rooms - create proper routes and controllers for rooms and messages
- [x] (9) Allow for multiple chat rooms - provide multiple chat room channels
- [x] (10) Provide simple list of all users
- [x] (11) Add broadcasting event for adding/removing a room
- [x] (12) Add functionality to update an existing room (name, members list)
- [x] (13) Make main chatroom name configurable
- [x] (14) Make Socialite callback URL more flexible: _[app_url]/login/{provider}/callback_
- [x] (15) Error after Google login callback (username missing when creating new user)
- [x] (16) Include Facebook as valid login provider
- [x] (17) Enable switch of locale (between English or German)
- [x] (18) choice of username is not working properly when logging in via Socialite
- [x] (19) send email to admin whenever a new user gets added
- [x] (20) use more random channel names to avoid clashes with other apps
