### ISSUE TITLE
ToDo List FrontEnd 

### ISSUE THREAD

**Issue by matthiku** [matthiku/chatter#2]
- [x] (26) Order the rooms by last update, with the newest at the top
- [x] (25) include `moment.js` to show message dates/times
- [x] (24) Enable switch of locale (between English or German)
- [x] (23) show a little space between the rooms and better design of header area
- [x] (22) set default name of a new room to the owner's name
- [x] (21) Add option for chat members (not the owner) to leave a room on their own
- [x] (20) instead of just removing a deleted chat, show a notification that it was deleted by the owner
- [x] (19) Allow users to delete their own messages (being replaced by a 'deleted' comment)
- [x] (18) not showing messages in a newly created room!
- [x] (17) Open a newly created room (make it not collapsed)
- [x] (16) when being added to an existing chat room, get all messages for this room
- [x] (15) improve design of messages
- [x] (14) indicate to others the owner of a room
- [x] (13) Ask for confirmation before finally deleting a Chat Room
- [x] (12) add a delete button to the Edit Room dialog
- [x] (11) when a room is removed, the listening channel should also be closed
- [x] (10) When a room is updated or added, check if the current user is member or not
- [x] (9) add logic and UI elements to add/remove users to a chat room
- [x] (8) Improve "Create new Room" dialog (button text, close the dialog)
- [x] (7) add new online users also to the generic list of users
- [x] (6) add logic and UI elements to delete a chat room (only by the owner)
- [x] (5) add logic and UI elements to create a new chat room
- [x] (4) provide simple list of all users
- [x] (3) show currently online users
- [x] (2) add logic to properly add messages to a chat
- [x] (1) Allow for multiple chat rooms and use Vuex for state management
