### ISSUE TITLE
ToDo List - Feature Requests

### ISSUE THREAD

**Issue by matthiku** [matthiku/chatter#3]
- [x] (1) Always push current chatroom to the top (basically when opening it)
- [x] (2) chat room to remain open when moved because of updates (new messages)
- [x] (3) show number of unread messages in the header and on the chatroom header
- [x] (4) open chatroom when only one is available
- [x] (5) Improve UI of dialog box for new chatrooms
- [x] (6) show a popup-menu on smaller devices to make out for the missing Username-Dropdown menu
- [x] (7) immediately open the newly created room
- [x] (8) Go to (closed) list of all chats when clicking onto header title text
- [x] (9) Go to new message and open chat when user clicks on red number of new messages
- [x] (10) Show number of chats in Title area as well, e.g. "My Chat Rooms (3)"
- [x] (11) Show name of current chat, number of unread messages and number of online users in page title
- [x] (12)  update Window title when a new message arrives into the currently open chatroom
- [x] (13) When chatroom is open, use highlighted and bigger font in room header 
- [x] (14) convert text that looks like a link to a real link
- [x] (15) Smileys support (convert ASCII smileys) and provide list of common ones
- [x] (16) show date/time of message in a format depending on age, e.g. today only show time etc.
- [x] (17) show "typing" besides user names if they are online and typing text into an open chatroom
- [x] (18) make the 'bin' icon in own messages light red and only dark red on hovering
- [x] (19) Show icons (avatar) of users in a chat
- [x] (20) Allow change of username
- [x] (21) keyboard - ESC - should get you out of a chatroom back to the chatrooms list
- [x] (22) scroll to bottom of all messages when opening chat room
- [x] (23) don't show name until the next msg is from a different user; don't show date of msgs from the same user written within 120 secs
- [x] (24) discover and re-direct to login when session has expired
- [x] (25) remove showing number of chatrooms in header bar and increase height of individ. chat header
- [x] (26) use a versioning system to see if clients have an outdated version

**Comment by AlexErling** [comment]
Hi, I am new to open source and was wondering if I could help you with your project!

**Comment by matthiku** [comment]
This is still in the alpha-stage, but if you have some experience with Laravel or Vue.js, that would greatly help!
Basically, you should be able to install and run the app locally in order to work on it (see the instructions on the project front page)

**Comment by AlexErling** [comment]
I've had some experience with Vue.js, but I am interested in learning more about it and whatever else is needed. I will follow the instructions now.
