### ISSUE TITLE
ToDo List - Bugs

### ISSUE THREAD

**Issue by matthiku** [matthiku/chatter#4]
- [x] (1) After renaming a chatroom it will appear twice in the list
- [x] (2) missing dates in the room_user pivotal table
- [x] (3) When deleting an open room, the displayed room list is empty, nothing is shown
- [x] (4) regularly check for a working presence channel
- [x] (5) properly handle success or error with subscribing to the chatroom presence channel
- [x] (6) newly created chatroom should appear at the top of the list
- [x] (7) clicking on the title of a just deleted chatroom should not open then next one
- [x] (8) don't open chatroom when user clicks on 'leaving room' icon
- [x] (9) Not properly removing a chat after being deleted
- [x] (10) Not properly opening a new chat right after creating one while another chat is open
- [x] (11) not properly updating reading progress after adding field to pivot table
